#!/bin/bash

function _couchpotato_install(){
	## Install system dependencies
	apt-get install git-core libffi-dev libssl-dev zlib1g-dev libxslt1-dev libxml2-dev python python-pip python-dev build-essential -y

	## Install python dependencies
	pip install lxml cryptography pyopenssl

	## Pull down Couchpotato repository
	git clone https://github.com/RuudBurger/CouchPotatoServer /opt/couchpotato

	## They recommend taking ownership with a user. I'm leaving root ownership for now.
	#chown -R ${USER}:${USER} /opt/couchpotato

	## They provide a default file. I'm using a pre-built for now
	cp /opt/couchpotato/init/ubuntu.default /etc/default/couchpotato

	cp /opt/couchpotato/init/ubuntu /etc/init.d/couchpotato

	chmod +x /etc/init.d/couchpotato

	update-rc.d couchpotato defaults
}

function _couchpotato_postconfig(){
	cp -f configs/couchpotato/couchpotato /etc/default/
}

