#!/bin/bash

function _couchpotato_install(){
	## Install system dependencies
	apt-get install git-core libffi-dev libssl-dev zlib1g-dev libxslt1-dev libxml2-dev python python-pip python-dev build-essential -y

	## Install python dependencies
	pip install lxml cryptography pyopenssl

	## Pull down Couchpotato repository
	git clone https://github.com/RuudBurger/CouchPotatoServer /opt/couchpotato

	## They recommend taking ownership with a user. I'm leaving root ownership for now.
	#chown -R ${USER}:${USER} /opt/couchpotato

	## They provide a default file for defaults. I will one with values added in post config (leaving for brevity)
	# cp /opt/couchpotato/init/ubuntu.default /etc/default/couchpotato

    ## Adding init scripts
	cp /opt/couchpotato/init/ubuntu /etc/init.d/couchpotato

	## Making scripts executable
	chmod +x /etc/init.d/couchpotato

	## Adding couchpotato to system startup
	update-rc.d couchpotato defaults
}

function _couchpotato_postconfig(){
	## Adding default configuration
	cp -f configs/couchpotato/couchpotato /etc/default/

	## Starting couchpotato
	service couchpotato start

	## Stopping couchpotato
	service couchpotato stop

	## Give service time to stop
	sleep 2

	## Adding url base "movies" for proxy handling
	cp -f configs/couchpotato/settings.conf /opt/couchpotato/settings.conf

	## Starting couchpotato
	service couchpotato start
}

