#!/bin/bash

function _install_all(){
	## Install CouchPotato
	_couchpotato_install
	_couchpotato_postconfig

	## Install HTPC Manager
	_htpc_install
	#_htpc_postconfig

	## Install Plex
	_plex_install

	## Install Sonarr
	_sonarr_install
	_sonarr_postconfig

	## Install NZBGet
	_nzbget_install
	_nzbget_postconfig

	## Install Apache
	_apache_install
	_apache_postconfig
}