#!/bin/bash

function _plex_install(){
	## Add repo key
	wget -O - http://shell.ninthgate.se/packages/shell-ninthgate-se-keyring.key | sudo apt-key add -

	## Add Plex repos
	echo "deb http://www.deb-multimedia.org wheezy main non-free" | tee -a /etc/apt/sources.list.d/deb-multimedia.list
	echo "deb http://shell.ninthgate.se/packages/debian wheezy main" | tee -a /etc/apt/sources.list.d/plex.list

	## Update repos
	apt-get update

	## Install dependencies
	apt-get install deb-multimedia-keyring -y --force-yes

	## Update repos
	apt-get update

	## Install Plex
	apt-get install plexmediaserver -y
}