#!/bin/bash

function _sick_install(){
    ## Install Dependencies
    apt-get install git-core python python-cheetah -y
    apt-get install unrar -y

    ## Download SickRage
    git clone git://github.com/echel0n/SickRage.git sickrage

    ## Add init script to system
    cp -f /opt/sickrage/init.ubuntu /etc/init.d/sickrage

    ## Copy default configuration to system
    cp -f configs/sickrage/sickrage /etc/default/sickbeard

    ## Set permissions on file
    chmod 755 /etc/init.d/sickbeard

    ## Add sickrage to system startup
    update-rc.d sickbeard defaults
}
